---
- name: Get controller host from environment variable CONTROLLER_HOST (https://controller_host)
  ansible.builtin.set_fact:
    controller_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
  delegate_to: localhost

- name: Set SAML settings
  ansible.controller.settings:
    settings:
      TOWER_URL_BASE: "{{ controller_host }}"
      SAML_AUTO_CREATE_OBJECTS: true
      SOCIAL_AUTH_SAML_CALLBACK_URL: "{{ controller_host }}/sso/complete/saml/"
      SOCIAL_AUTH_SAML_METADATA_URL: "{{ controller_host }}/sso/metadata/saml/"
      SOCIAL_AUTH_SAML_SP_ENTITY_ID: "{{ controller_host }}"
      SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: "{{ lookup('ansible.builtin.file', 'saml.crt') }}"
      SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: "{{ lookup('ansible.builtin.file', 'saml.key') }}"
      SOCIAL_AUTH_SAML_TECHNICAL_CONTACT:
        givenName: "{{ givenName }}"
        emailAddress: "{{ emailAddress }}"
      SOCIAL_AUTH_SAML_SUPPORT_CONTACT:
        givenName: "{{ givenName }}"
        emailAddress: "{{ emailAddress }}"
      SOCIAL_AUTH_SAML_ORG_INFO:
        en-US:
          url: "{{ controller_host }}"
          name: "{{ name }}"
          displayname: "{{ displayname }}"
      SOCIAL_AUTH_SAML_ENABLED_IDPS:
        example-userpass:
          x509cert: "{{ lookup('ansible.builtin.file', 'saml.crt') | regex_replace('-----BEGIN CERTIFICATE-----\n', '') | regex_replace('\n-----END CERTIFICATE-----', '') }}"
          url: "{{ idp_host }}/simplesaml/saml2/idp/SSOService.php"
          entity_id: "{{ idp_host }}/simplesaml/saml2/idp/metadata.php"
          attr_email: "email"
          attr_username: "user_name"
          attr_last_name: "last_name"
          attr_first_name: "first_name"
      SOCIAL_AUTH_SAML_SECURITY_CONFIG:
        requestedAuthnContext: true
      SOCIAL_AUTH_SAML_TEAM_ATTR:
        remove: true
        saml_attr: eduPersonAffiliation
        team_org_map:
          - team: group1
            organization: Default
          - team: group2
            organization: Default
    validate_certs: false
  become: false
  delegate_to: localhost
