---
- name: Run OpenLDAP container with Podman (parameterized, plain-text password)
  hosts: localhost
  become: true
  vars:
    ldap_image: docker.io/osixia/openldap:1.5.0
    ldap_container_name: testldap
    ldap_ports:
      - "389:389"
      - "636:636"
    ldap_org: "Example Inc."
    ldap_domain: "example.org"
    ldap_admin_password: "admin"
    ldap_bootstrap_ldif: "bootstrap.ldif"
    container_bootstrap_ldif: "/ldif/50-bootstrap.ldif"
    ldap_server: "ldap://10.0.0.101:389"

  tasks:
    - name: Bring up LDAP container and configure the Ansible Controller to use it
      ansible.builtin.include_role:
        name: ldap

    - name: Bring up SAML container and configure the Ansible Controller to use it
      ansible.builtin.include_role:
        name: saml
      vars:
        idp_host: "http://10.0.0.101:8080"
        entity_url: "https://192.168.122.82/sso/complete/saml/"