---
- name: Run SimpleSAMLphp IdP container with Podman (parameterized)
  hosts: localhost
  become: true
  vars:
    idp_image: kenchan0130/simplesamlphp
    idp_container_name: testsamlidp

    # Paths to config, metadata, and cert files (host side)
    authsources_file: "./config/authsources.php"
    config_file: "./config/config.php"
    metadata_file: "./metadata/saml20-idp-hosted.php"
    saml_key_file: "./certs/saml.key"
    saml_crt_file: "./certs/saml.crt"

    # Paths inside the container
    container_authsources: "/var/www/simplesamlphp/config/authsources.php:Z"
    container_config: "/var/www/simplesamlphp/config/config.php:Z"
    container_metadata: "/var/www/simplesamlphp/metadata/saml20-idp-hosted.php:Z"
    container_saml_key: "/var/www/simplesamlphp/cert/saml.key:Z"
    container_saml_crt: "/var/www/simplesamlphp/cert/saml.crt:Z"

    # Ports
    idp_ports:
      - "8080:8080"
      - "8443:8443"

    # Environment variables / URLs
    # It changes once SAML migrates from 2.4 old urls to 2.5
    #sp_entity_id: "https://192.168.122.85"
    #sp_acs_url: "https://192.168.122.85/sso/complete/saml/"
    sp_entity_id: "https://192.168.122.30"
    sp_acs_url: "https://192.168.122.30/api/gateway/social/complete/1dca1e05-1280-43d3-9f51-549561c24012/"

  tasks:
    - name: Ensure SimpleSAMLphp IdP container is running
      containers.podman.podman_container:
        name: "{{ idp_container_name }}"
        image: "{{ idp_image }}"
        state: started
        recreate: true
        detach: true
        ports: "{{ idp_ports }}"
        volume:
          - "{{ authsources_file }}:{{ container_authsources }}"
          - "{{ config_file }}:{{ container_config }}"
          - "{{ metadata_file }}:{{ container_metadata }}"
          - "{{ saml_key_file }}:{{ container_saml_key }}"
          - "{{ saml_crt_file }}:{{ container_saml_crt }}"
        env:
          SIMPLESAMLPHP_SP_ENTITY_ID: "{{ sp_entity_id }}"
          SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "{{ sp_acs_url }}"

